# Note \hfill `(._. )`

Queste note sono state prese dal sottoscritto durante le lezioni del corso di *Elementi di calcolabilità e complessità* tenuto dal prof. Pierpaolo Degano con l'ausilio del dott. Giulio Masetti durante l'anno accademico 2019-2020.

Il materiale usato per la stesura, oltre alle note distribuite dal professore, comprende, in maniera più o meno estensiva, i seguenti testi:

* Introduction to the theory of computation - Sipser
* Computability, introduction to recursive function theory - Cutland
* Introduzione alla complessità computazionale - Bernasconi, Codenotti
* Linguaggi, modelli, complessità - Ausiello, d'Amore, Gambosi




---




###### Pierpaolo Degano

> \faHome\quad ufficio 285, dipartimento di Informatica\
> \faGlobe\quad `di.unipi.it/~degano`\
> \faPaperPlaneO\quad `degano@unipi.di.it`\
> \faPhone\quad 050 221 2757\

###### Giulio Masetti

> \faHome\quad ufficio I-25, edificio B, CNR\
> \faPaperPlaneO\quad `giulio.masetti@isti.cnr.it`\

###### Matteo Giorgi (me)

> \faGlobe\quad `matteogiorgi.github.io`\
> \faPaperPlaneO\quad `matteo.giorgi@protonmail.com`\

