# Lezione 01 \hfill `2020.02.17`




## Idea intuitiva di algoritmo

Il punto di partenza della teoria della calcolabilità è l'esigenza di formalizzare l'idea intuitiva di *funzione calcolabile* da un algoritmo, ovvero di *funzione algoritmica*[^1].

Si può dire che un algoritmo sia un procedimento di calcolo che consenta di pervenire alla soluzione di un problema, numerico o simbolico, mediante una sequenza finita di operazioni, completamente e univocamente determinate: una serie di istruzioni la cui esecuzione consenta di trasformare l'insieme finito di dati simbolici che descrivono il problema, nella soluzione del problema stesso.

### Caratteristiche distintive

1. l'insieme delle istruzioni che definisce l'algoritmo è finito
2. l'insieme delle informazioni che rappresentano il problema
    * ha cardinalità finita
    * ha un effetto limitato su dati discreti
    * è descritta da dati finiti
3. il procedimento di calcolo (o *computazione*) è suddiviso in passi discreti e non fa uso di dispositivi analogici
4. ogni passo di computazione dipende solo dai precedenti e da una porzione finita dei dati in modo deterministico (è determinato senza ambiguità - non è soggetto ad alcuna distribuzione probabilistica non banale)
5. non c'è limite al numero di passi necessari all'esecuzione di un algoritmo, nè alla memoria richiesta per contenere i dati iniziali, intermedi e finali[^2]

In conclusione, una procedura algoritmica riceve in ingresso una descrizione finita dei dati del problema e restituisce, dopo un tempo finito, una descrizione finita del risultato. La sua natura deterministica fa sì che l'algoritmo fornisca sempre lo stesso risultato ogni volta che riceve in ingresso gli stessi dati: così facendo l'algoritmo stabilisce una relazione funzionale tra l'insieme dei dati e quello dei risultati.

[^1]: la nozione di funzione algoritmica sarà poi formalizzata dal concetto di *funzione ricorsiva*
[^2]: è utile aggiungere una ulteriore caratteristica a quelle elencate dal prof: *esiste un agente di calcolo in grado di eseguire le istruzioni (una calcolatore)*




## Macchina di Turing

Esattamente come *funzioni ricorsive* e *$\lambda$-calcolo*, le Macchine di Turing sono un modello di calcolo. Nella sua versione più tradizionale una *MdT* si presenta come un dispositivo che accede ad un nastro potenzialmente illimitato diviso in celle, ciascuna contenente un simbolo appartenente ad un dato alfabeto $\Sigma$ (alfabeto della macchina), comprendente i simboli $\#$ e $\triangleright$ che denotano rispettivamente l'assenza di informazione nella cella e la marca di inizio stringa:

* la MdT opera tramite un *cursore*, che può scorrere sul nastro in entrambe le direzioni e scrivere i caratteri $\sigma_i$ appartenenti all'alfabeto $\Sigma$.

* gli *stati* $q_i$ della macchina appartengono all'insieme finito degli stati $Q$ e identificano le configurazioni istante per istante della macchina (posizione cursore, carattere letto, informazioni memoria).

>> $\triangleright\  a\ b\ ...\ a\ \underline{a}\ b\ \#\ \#$

* il meccanismo che fa evolvere la computazione della macchina è detta *funzione di transizione*[^3] $\delta$ e  permette, partendo dallo stato $q_x$ attuale e dal carattere $\sigma_x$ presente sulla cella puntata dala testina, di portare la macchina in un'altro stato $q_y$, scrivere un carattere $\sigma_y$ su tale cella precedentemente occupata da $\sigma_x$ ed eventualmente spostare la testina ($\Lleftarrow$, $\Rrightarrow$, $\equiv$).

\begin{definition}
una \underline{Macchina di Turing} è definita  formalmente come la quadrupla
$$
M = (Q, \Sigma, \delta, q_0)
$$
\textit{potrebbe essere conveniente modificare la definizione di MdT estendendo la quadrupla ad una quintupla togliendo gli stati di accettazione e rifiuto dall'insieme $Q$, aggiungendoli in un insieme a parte: $M = (Q\backslash \{q_A,q_R\}, \Sigma, \delta, q_0, \{q_A,q_R\})$. Così facendo evito che la macchina vada in stallo.}

\begin{itemize}[itemsep=-7pt]
    \item $Q$ è l'insieme finito degli stati $q_i$ che non contiene lo stato di accettazione $h$
    \item $\Sigma$ è l'insieme finito dei simboli (alfabeto della macchina) al quale non appartengono i simboli di spostamento $\Lleftarrow$, $\Rrightarrow$, $\equiv$
    \item $\delta\subseteq (Q \times \Sigma)\times (Q \cup {h}) \times \Sigma \times \{\Lleftarrow,\Rrightarrow,\equiv\}$ è la relazione di transizione, tale che il carattere puntato dal cursore non possa mai trovarsi a sinistra di $\triangleright$ 
    \item $q_0 \in Q$ è lo stato iniziale
\end{itemize}
\end{definition}

[^3]: fintanto che verranno trattare MdT deterministiche non è errato considerare $\delta$ una funzione piuttosto di una più generica relazione

