# Algoritmi e Macchine

\thispagestyle{empty}








## Idea intuitiva di algoritmo

Il punto di partenza della teoria della calcolabilità è l'esigenza di formalizzare l'idea intuitiva di *funzione calcolabile* da un algoritmo, ovvero di *funzione algoritmica*[^1].

Si può dire che un algoritmo sia un procedimento di calcolo che consente di pervenire alla soluzione di un problema, numerico o simbolico, mediante una sequenza finita di operazioni, completamente e univocamente determinate: una serie di istruzioni la cui esecuzione consente di trasformare l'insieme finito di dati simbolici che descrivono il problema, nella soluzione del problema stesso.








### Caratteristiche distintive[^2]

1. l'insieme delle istruzioni che definisce l'algoritmo è finito
2. l'insieme delle informazioni che rappresentano il problema
    * ha cardinalità finita
    * ha un effetto limitato su dati discreti
    * è descritta da dati finiti
3. il procedimento di calcolo (o *computazione*) è suddiviso in passi discreti e non fa uso di dispositivi analogici
4. ogni passo di computazione dipende solo dai precedenti e da una porzione finita dei dati in modo deterministico (è determinato senza ambiguità ovvero non soggetto ad alcuna distribuzione probabilistica non banale)
5. non c'è limite al numero di passi necessari all'esecuzione di un algoritmo, nè alla memoria richiesta per contenere i dati iniziali, intermedi e finali

In conclusione, una procedura algoritmica riceve in ingresso una descrizione finita dei dati del problema e restituisce, dopo un tempo finito, una descrizione finita del risultato. La sua natura deterministica fa sì che l'algoritmo fornisca sempre lo stesso risultato ogni volta che riceve in ingresso gli stessi dati: così facendo stabilisce una relazione funzionale tra l'insieme dei dati e quello dei risultati.








## Macchina di Turing

Esattamente come *funzioni ricorsive* e *$\lambda$-calcolo*, le Macchine di Turing sono un modello di calcolo. Nella sua versione più tradizionale una *MdT* si presenta come un dispositivo che accede ad un nastro potenzialmente illimitato diviso in celle, ciascuna contenente un simbolo appartenente ad un dato alfabeto $\Sigma$ (alfabeto della macchina), comprendente i simboli `#` e `>` che denotano rispettivamente l'assenza di informazione nella cella e la marca di inizio stringa.
\begin{equation*}
\texttt{>}\, \texttt{a}\, \texttt{b}\, ...\, \texttt{a}\, \pointer{\texttt{b}}\, \texttt{b\,\#\,\#}
\end{equation*}

* la MdT opera tramite un *cursore*, che può scorrere sul nastro in entrambe le direzioni e scrivere i caratteri $\sigma_i$ appartenenti all'alfabeto $\Sigma$

* gli *stati* $q_i$ della macchina appartengono all'insieme finito degli stati $Q$ e identificano istante per istante le informazioni contenute nella computazione

* il meccanismo che fa evolvere la computazione della macchina è detta *funzione di transizione*[^3] $\delta$ e consente, partendo dallo stato $q_x$ e dal carattere $\sigma_x$ presente sulla cella puntata dalla testina, di portare la macchina in un altro stato $q_y$, scrivere un carattere $\sigma_y$ su tale cella precedentemente occupata da $\sigma_x$ ed eventualmente spostare la testina ($\Lleftarrow$, $\Rrightarrow$, $\equiv$)

\begin{definition}
Una \underline{Macchina di Turing} è definita  formalmente come la quadrupla
\begin{equation*}
M = (Q, \Sigma, \delta, q_0)
\end{equation*}

\begin{itemize}[itemsep=-7pt]
\item $Q$ è l'insieme finito degli stati $q_i$ tale che lo stato di accettazione $h{\notin}Q$
\item $\Sigma$ è l'insieme finito dei simboli (alfabeto della macchina) al quale non appartengono i simboli di spostamento $\Lleftarrow$, $\Rrightarrow$, $\equiv$
\item $\delta\,{\subseteq}\,(Q\,{\times}\,\Sigma)\,{\times}\,(Q\,{\cup}\,{h})\,{\times}\,\Sigma\,{\times}\,\{\Lleftarrow,\Rrightarrow,\equiv\}$ è la relazione di transizione, tale che il carattere puntato non possa mai trovarsi a sinistra di \textnormal{\ttfamily >}
\item $q_0\,{\in}\,Q$ è lo stato iniziale
\end{itemize}
\end{definition}








## Configurazione, transizione e computazione

\begin{definition}
Una \underline{configurazione} (istantanea) $C$ di una MdT è definita dalla quadrupla
\begin{gather*}
(q,u,\sigma,v) \in (Q \cup \{h\}) \times \Sigma^* \times \Sigma \times \Sigma^F \\
\colorbox{gray85}{\qquad u \qquad}\ \sigma\ \colorbox{gray85}{\qquad v \qquad}
\end{gather*}

\begin{itemize}[itemsep=-7pt]
\item $q$ è lo stato corrente
\item $\sigma$ è il simbolo corrente
\item $u$ è la stringa di caratteri a sinistra del simbolo corrente
\item $v$ è la stringa di caratteri a destra del simbolo corrente
\end{itemize}
\end{definition}

Ne viene intuitivo dedurre che $\Sigma^*$ rappresenti l'insieme di cardinalità infinita delle stringhe generabili dalla \textit{concatenazione}[^4] dei caratteri dell'alfabeto della macchina $\Sigma$, mentre $\Sigma^F$ è più facile a scriversi che a dirsi:
\begin{equation*}
\Sigma^F = \Sigma^* \circ \big(\Sigma{\backslash}\{\textnormal{\texttt{\#}}\}\big) \cup \{\epsilon\}
\end{equation*}
In generale una configurazione di una MdT non è altro che la coppia formata dallo stato corrente della macchina più la stringa[^5] rappresentante la situazione sul nastro.








### $\delta$ come funzione

Alla luce delle definizioni di MdT e configurazione, è importante analizzare meglio la relazione di transizione $\delta$, definita precedentemente come la quadrupla
\begin{equation*}
\big((q_x,\sigma_x),q_y,\sigma_y,D\big)
\end{equation*}

* $(q_x,\sigma_x)$ è la coppia stato di partenza, carattere puntato dal cursore
* $q_y$ è lo stato di arrivo
* $\sigma_y$ è il carattere scritto nella cella precedentemente occupata da $\sigma_x$
* $D$ è lo spostamento del cursore ($\Lleftarrow$, $\Rrightarrow$, $\equiv$)

Adesso è facilmente intuibile che, una macchina nella medesima configurazione di partenza che compie il medesimo spostamento del cursore, si troverà nella medesima configurazione di arrivo.

Questa constatazione permette di restringere la relazione $\delta$ in modo che sia una funzione rispetto al suo primo argomento (coppia stato corrente, carattere letto):
\begin{equation*}
\delta(q_x,\sigma_x)=(q_y,\sigma_y,D)
\end{equation*}








### Una nuova definizione di MdT

Prima di procedere, è necessario utilizzare le considerazioni fatte fin'ora e ritoccare la nostra definizione di MdT estendendo la quadrupla ad una quintupla con l'introduzione di $\{q_A,q_R\}$; questo facilitarà il nostro percorso nell'utilizzo di macchine e linguagi regolari come strumento per trattare la classe dei *problemi decisionali*.

\begin{definition}
Una \underline{Macchina di Turing deterministica} è definita come la quintupla
\begin{equation*}
M = (Q, \Sigma, \delta, q_0, \{q_A,q_R\})
\end{equation*}

\begin{itemize}[itemsep=-7pt]
\item $Q$ è l'insieme finito degli stati $q_i$ che non contiene gli stati terminali
\item $\Sigma\,{\nsupseteq}\,\{\Lleftarrow,\Rrightarrow,\equiv\}$ è sempre l'insieme finito dei simboli
\item $\delta\,{:}\,(Q\,{\times}\,\Sigma)\,{\rightarrow}\,(Q\,{\times}\,\Sigma\,{\times}\,\{\Lleftarrow,\Rrightarrow,\equiv\})$ è la funzione di transizione
\item $q_0\,{\in}\,Q$ è lo stato iniziale
\item $\{q_A,q_R\}\,{\nsubseteq}\,Q$ è l'insieme degli stati terminali di accettazione e rifiuto
\end{itemize}
\end{definition}








### Computazione e passo di computazione

\begin{definition}
Una \underline{computazione} di una MdT è costituita da una sequenza di configurazioni, tale che $C_0$ rappresenti la configurazione iniziale e $C_{i+1}$ il risultato dell'applicazione della funzione $\delta$ alla configurazione $C_i$ (ovvero il \underline{passo di computazione} $C_i{\rightarrow}C_{i+1}$). Si dirà inoltre che la computazione converge $\downarrow$ se, per $n{\ge}1$ tale che
\begin{equation*}
C_0 \rightarrow C_1 \rightarrow ... \rightarrow C_n
\end{equation*}
$C_n$ è una configurazione finale, in caso contrario si dirà che diverge $\uparrow$.
\end{definition}

Per completezza, dato che un passo di computazione di una macchina $M$ può essere visto come una relazione $\rightarrow_M$ tra $C_i$ e $C_{i+1}$, una computazione di $M$ è definibile come la *chiusura riflessiva e transitiva*[^6] di $\rightarrow_M$ che, in accordo con la notazione usata precedentemente, può essere scritta come
\begin{equation*}
C_0 \rightarrow_M^* C_n
\end{equation*}








### Esempio di MdT

Consideriamo una macchina $M$ che calcoli la somma di due numeri naturali scritti in notazione unaria usando il simbolo `|` e separati dal simbolo `+`. La seguente successione di configurazioni rappresenterà la computazione $(q_0, \pointer{\texttt{>}} \texttt{|+||\#}){\rightarrow^*_M}(h, \texttt{>} \texttt{|||} \pointer{\texttt{\#}})$
\begin{align*}
(q_0,\ \pointer{\texttt{>}}\, \texttt{|\,+\,|\,|\,\#})\ &\longrightarrow\ (q_0,\ \texttt{>}\, \pointer{\texttt{|}}\, \texttt{+\,|\,|})\\
                                                        &\longrightarrow\ (q_0,\ \texttt{>}\, \texttt{|}\, \pointer{\texttt{+}}\, \texttt{|\,|})\\
                                                        &\longrightarrow\ (q_1,\ \texttt{>}\, \texttt{|\,|}\, \pointer{\texttt{|}}\, \texttt{|})\\
                                                        &\longrightarrow\ (q_1,\ \texttt{>}\, \texttt{|\,|\,|}\, \pointer{\texttt{|}})\\
                                                        &\longrightarrow\ (q_1,\ \texttt{>}\, \texttt{|\,|\,|\,|}\, \pointer{\texttt{\#}})\\
                                                        &\longrightarrow\ (q_2,\ \texttt{>}\, \texttt{|\,|\,|}\, \pointer{\texttt{|}})\\
                                                        &\longrightarrow\ (h,\ \texttt{>}\, \texttt{|\,|\,|}\, \pointer{\texttt{\#}})
\end{align*}
Dalla precedente posso facilmente tabulare la funzione $\delta$, mentre la successione degli stati esplorati dalla macchina sono rappresentabili con un automa finito.

\vspace{30pt}

| $q$ | $\sigma$ | $\delta$ |
| :---: | :---: | :---: |
| $q_0$ | `>` | $q_0$, `>`, $\Rrightarrow$ |
| $q_0$ | `|` | $q_0$, `|`, $\Rrightarrow$ |
| $q_0$ | `+` | $q_1$, `|`, $\Rrightarrow$ |
| $q_1$ | `|` | $q_1$, `|`, $\Rrightarrow$ |
| $q_1$ | `#` | $q_2$, `#`, $\Lleftarrow$ |
| $q_2$ | `|` | $h$, `#`, $\equiv$ |

\vspace{30pt}

\begin{center}
\begin{tikzpicture}[scale=0.2]
\tikzstyle{every node}+=[inner sep=0pt]
\draw [black] (20.6,-29.6) circle (3);
\draw (20.6,-29.6) node {$q_0$};
\draw [black] (34.9,-29.6) circle (3);
\draw (34.9,-29.6) node {$q_1$};
\draw [black] (48.9,-29.6) circle (3);
\draw (48.9,-29.6) node {$q_2$};
\draw [black] (62.9,-29.6) circle (3);
\draw (62.9,-29.6) node {$h$};
\draw [black] (62.9,-29.6) circle (2.4);
\draw [black] (13.4,-29.6) -- (17.6,-29.6);
\fill [black] (17.6,-29.6) -- (16.8,-29.1) -- (16.8,-30.1);
\draw [black] (23.6,-29.6) -- (31.9,-29.6);
\fill [black] (31.9,-29.6) -- (31.1,-29.1) -- (31.1,-30.1);
\draw (27.75,-29.1) node [above] {\texttt{+}};
\draw [black] (37.9,-29.6) -- (45.9,-29.6);
\fill [black] (45.9,-29.6) -- (45.1,-29.1) -- (45.1,-30.1);
\draw (41.9,-29.1) node [above] {\texttt{\#}};
\draw [black] (51.9,-29.6) -- (59.9,-29.6);
\fill [black] (59.9,-29.6) -- (59.1,-29.1) -- (59.1,-30.1);
\draw (55.9,-29.1) node [above] {\texttt{|}};
\draw [black] (21.923,-32.28) arc (54:-234:2.25);
\draw (20.6,-36.85) node [below] {\texttt{>},\texttt{|}};
\fill [black] (19.28,-32.28) -- (18.4,-32.63) -- (19.21,-33.22);
\draw [black] (36.223,-32.28) arc (54:-234:2.25);
\draw (34.9,-36.85) node [below] {\texttt{|}};
\fill [black] (33.58,-32.28) -- (32.7,-32.63) -- (33.51,-33.22);
\end{tikzpicture}
\end{center}








[^1]: La nozione di funzione algoritmica sarà poi formalizzata dal concetto di *funzione ricorsiva*.
[^2]: Può essere utile aggiungere una ulteriore caratteristica a quelle elencate dal prof: *esiste un agente di calcolo in grado di eseguire le istruzioni (il calcolatore)*.
[^3]: Nel trattare MdT deterministiche (quelle definite in questo capitolo) non è errato considerare $\delta$ come una funzione. La definizione formale fa riferimento a MdT nastro singolo, comprese quelle non-deterministiche dove $\delta$ restituisce un insieme di possibili configurazioni successive: ecco perchè sarà poi introdotta come relazione.
[^4]: Antepone due stringhe di $\Sigma$ in tutti i modi possibili ($\Sigma^*{=}\Sigma{\circ}\Sigma$). Vedi *operazioni regolari*.
[^5]: Quando verranno trattate macchine a $k$ nastri, si parlerà di una k-upla di stringhe, ciascuna delle quali riferita ad un nastro della macchina.
[^6]: La chiusura riflessiva e transitiva $\bar{R}$ di una relazione $R$ è definita come $\bar{R}{=}\cap_{R{\subseteq}S}S$, dove $S$ sia anch'essa relazione riflessiva e transitiva. Alternativamente la può pensare come la più piccola relazione definita per induzione attraverso le seguenti proposizioni
\begin{itemize}[itemsep=-3pt]
\item $\forall\, a{\in}A\, .\, \exists\bar{R}(a,a)$
\item $R(a,b)\, {\Rightarrow}\, \bar{R}(a,b)$
\item $\bar{R}(a,b)\, {\wedge}\, \bar{R}(b,c)\, {\Rightarrow}\, \bar{R}(a,c)$
\end{itemize}
\noindent Prova a dimostrare l'equivalenza delle due definizioni \faMehO.
