# Decidibilità

\thispagestyle{empty}








## Linguaggi T-riconoscibili e T-decidibili

Dopo la parentesi fatta sugli automi, sono perfettamente in grado di puntualizzare quanto definito in precedenza riguardo le stringhe accettate da una macchina.

\begin{definition}
Sia $M{=}(Q,\Sigma,\delta,q_0,\{q_A,q_R\})$ una MdT e $w{=}w_0w_1...w_n$ una stringa composta da caratteri $w_i{\in}\Sigma$. Si dice che $M$ \underline{accetta} la stringa $w$ se esiste una sequenza di configurazioni $[C_0,C_1,...,C_n]$ tale che

\begin{enumerate}[itemsep=-7pt]
\item $C_0$ è la configurazione iniziale su input $w$ \hfill $\exists\, C_0$ inizio
\item Ogni $C_i$ produce $C_{i+1}$ \hfill $C_i\,{\rightarrow}\,C_{i+1}$
\item $C_n$ è una configurazione di accettazione \hfill $\exists\, C_n$ accett.
\end{enumerate}

Esattamente come detto prima $M$ \underline{riconosce} un linguaggio $A$ se ne accetta tutte le sue stringhe. Si scriverà $A{=}L(M)$.
\end{definition}

Appare chiaro che sono tre i risultati possibili per una MdT: *accettare*, *rifiutare* oppure andare in *loop*[^10]. Quindi fai attenzione perchè una macchina $M$ può non accettare un input sia raggiungendo lo stato $q_R$ che andando in loop.

A volte distinguere una macchina che è entrata in un loop da una che sta semplicemente impiegando molto tempo risulta difficile, per questo sono preferibili MdT che si fermano su ogni singolo input. Una tale macchina è detta *decisore* e diremo che decide un certo linguaggio se lo riconosce.

\begin{definition}
Un linguaggio si dice \underline{Turing-riconoscibile} sse esiste una MdT che lo riconosce (ovvero, per ogni stringa del linguaggio la machina termina nello stato di accettazione).
\end{definition}

\begin{definition}
Un linguaggio si dice \underline{Turing-decidibile} sse esiste una MdT che lo decide (ovvero, per ogni stringa del linguaggio la macchina termina nello stato di accettazione, per tutte le altre termina nello stato si rifiuto).
\end{definition}

\begin{theorem}
Ogni linguaggio Turing-decidibile è Turing-riconoscibile.
\begin{proof}
Segue direttamente dalle due definizioni: se è decidibile significa che raggiunge lo stato di accettazione per tutte le stringhe del linguaggio, quindi è Turing-riconoscibile.
\end{proof}
\end{theorem}








### Cosa posso decidere?

Di seguito darò alcuni esempi di linguaggi Turing-decidibili; si renderanno utili le precedenti pagine sugli automi finiti e le definizioni di riconoscibilità e decidibilità.

I problemi computazionali proposti, a partire da quello dell'*accettazione* qua sotto, verranno rappresentati mediante linguaggi; si tratterà quindi di scrivere il problema in questione come un insieme di stringhe e chiedersi se esiste una MdT che decide tale linguaggio[^11]. Mostrare dunque che il linguaggio è decidibile equivale a mostrare che il problema computazionale è decidibile.

\begin{lemma}
Sia $A_{DFA}$ il linguaggio contenente le coppie formate dalle codifiche di tutti i DFA con delle particolari stringhe che essi accettano
\begin{equation*}
A_{DFA} = \{\langle B,w\rangle\ |\ \text{$B$ è un DFA che accetta la stringa in input $w$}\}
\end{equation*}
$A_{DFA}$ è un linguaggio decidibile.
\begin{proof}
L'idea è quella di presentare una MdT $M$ che decide $A_{DFA}$. $M$ deve prendere come input la coppia $\langle B,w\rangle$, simulare $B$ su $w$ e accettare se la simulazione termina in uno stato di accettazione, viceversa rifiutare.

Quindi, dopo aver controllato la validità della coppia in input, $M$ esegue la simulazione: tiene traccia dello stato corrente di $B$ e della sua posizione corrente nell'input $w$ scrivendo queste informazioni sul nastro, usa la funzione di transizione per aggiornare stati e posizioni fin quando non termina l'elaborazione dell'ultimo simbolo di $w$. $M$ accetta l'input se $B$ si trova in uno stato di accettazione, rifiuta altrimenti.
\end{proof}
\end{lemma}

\begin{lemma}
Sia $A_{NFA}$ il linguaggio contenente le coppie formate dalle codifiche di tutti gli NFA con delle particolari stringhe che essi accettano
\begin{equation*}
A_{NFA} = \{\langle B,w\rangle\ |\ \text{$B$ è un NFA che accetta la stringa in input $w$}\}
\end{equation*}
$A_{NFA}$ è un linguaggio decidibile.
\begin{proof}
Presentiamo una MdT $N$ che decide $A_{NFA}$. $N$ converte l'NFA $B$ in un DFA $C$ equivalente, esegue $M$ come una sottoprocedura che decide $A_{DFA}$ su input $\langle C,w\rangle$ e accetta se $M$ accetta, altrimenti rifiuta.
\end{proof}
\end{lemma}

Con il prossimo problema, chiamato *test del vuoto* per il linguaggio di un automa finito, si vuove determinare se un DFA accetta una qualche stringa.

\begin{lemma}
Sia $E_{DFA}$ il linguaggio contenente le codifiche di tutti i DFA che non accettano alcuna stringa
\begin{equation*}
E_{DFA} = \{\langle A\rangle\ |\ \text{$A$ è un DFA e $L(A)\,{=}\,\emptyset$}\}
\end{equation*}
$E_{DFA}$ è un linguaggio decidibile.
\begin{proof}
Ciascun DFA accetta almeno una stringa sse dallo stato iniziale è possibile raggiungere uno stato di accettazione percorrendo il verso delle freccie; posso quindi trattare i DFA come grafi connessi orientati e progettare una MdT $T$ che esegua la marcatura degli stati per implementare tale controllo.

$T$ marca lo stato iniziale e, successivamente, marca tutti gli stati che hanno una transizione proveniente da uno stato già marcato finchè non si esauriscono gli stati inesplorati. Se nessuno stato di accettazione è marcato accetta, altrimenti rifiuta.
\end{proof}
\end{lemma}

\begin{lemma}
Sia $EQ_{DFA}$ il linguaggio contenente tutte le coppie formate dalle codifiche di due DFA che riconoscono lo stesso linguaggio
\begin{equation*}
EQ_{DFA} = \{\langle A,B\rangle\ |\ \text{$A$ e $B$ sono DFA tali che $L(A)\,{=}\,L(B)$}\}
\end{equation*}
$EQ_{DFA}$ è un linguaggio decidibile.
\begin{proof}
A partire da $A$ e $B$ costruisco un nuovo DFA $C$ che accetta solo quella stringhe che sono accettate da $A$ o da $B$ ma non da entrambi. In particolare, se $A$ e $B$ riconoscono lo stesso linguaggio, $C$ non accetterà nulla
\begin{gather*}
L(C) = \big( L(A) \cap \overline{L(B)} \big) \cup \big( \overline{L(A)} \cap L(B) \big)\\
\text{ovvero}\ L(C)\,{=}\,\emptyset\ \Leftrightarrow\ L(A)\,{=}\,L(B)
\end{gather*}
Non resta che costruire una MdT $F$ che verifica questa implicazione usando il lemma precedente. $F$ prende in input $\langle A,B\rangle$, costruisce il DFA $C$, esegue la MdT $T$ per decidere $E_{DFA}$ su input $\langle C\rangle$ e accetta se $T$ accetta, viceversa rifiuta.
\end{proof}
\end{lemma}








## Cosa *non* posso decidere?

Che succederebbe se adesso usassi la codifica di una MdT invece che quella di un automa? Posso determinare se una MdT accetta una determinata stringa?

Lo scopo di questo paragrafo sarà quindi quello di dimostrare che il linguaggio contenente le coppie formate dalle codifiche di tutte le MdT con delle particolari stringhe che essi accettano è indecidibile[^12].








### Il metodo della diagonalizzazione

Misurare la dimensione di insiemi finiti è relativamente facile, è sufficiente contare gli elementi contenuti in ciascuno ma con insiemi di cardinalità infinita, le cose si complicano. La soluzione sarà quella di mostrare una bigezione tra due insiemi di equa cardinalità.

\begin{definition}
Un insieme $A$ è numerabile se è finito o ha la stessa cardinalità di $\mathcal{N}$.
\end{definition}

\normalsize Curabitur urna tellus, aliquam vitae, ultrices eget, vehicula nec, diam.
Integer elementum, felis non faucibus euismod, erat massa dictum eros, eu
ornare ligula tortor et mauris. Cras molestie magna in nibh. Aenean et tellus.
Fusce adipiscing commodo erat. In eu justo. Nulla dictum, erat sed blandit
venenatis, arcu dolor molestie.
\small Taciti sociosqu ad litora torquent per conubia nostra, per inceptos
himenaeos. Nulla lectus sem, tristique sed, semper in, hendrerit non, sem.
Vivamus dignissim massa in ipsum. Morbi fringilla ullamcorper ligula. Nunc
turpis. Mauris vitae sapien. Nunc luctus bibendum velit.
metus at mi mollis posuere. Quisque ac.
\footnotesize Non neque. Suspendisse et diam. Sed vestibulum malesuada ipsum.
Pellentesque quis leo eget ante tempor cursus. Pellentesque sagittis, diam ut
dictum accumsan, magna est viverra erat, vitae imperdiet neque mauris aliquam
nisl. Suspendisse blandit quam quis felis. Praesent turpis nunc, vehicula in,
bibendum vitae, blandit ac, turpis. Duis rhoncus. Vestibulum metus. Morbi
consectetuer felis id tortor. Etiam augue leo, cursus eget, ornare et, ornare
sagittis, tellus. Fusce felis tellus, consectetuer nec, consequat.
\scriptsize Nulla sed lectus. Morbi sollicitudin, diam ac bibendum scelerisque,
enim tortor rhoncus sapien, vel posuere dolor neque in sem. Pellentesque tellus
augue, tempus nec, laoreet at, porttitor blandit, leo. Phasellus in odio. Duis
lobortis, metus eu laoreet tristique, pede mi congue mi, quis posuere augue
nulla a augue. Pellentesque sed est. Mauris cursus urna id lectus. Integer
dignissim feugiat eros. Sed tempor volutpat dolor. Vestibulum vel lectus nec
mauris semper adipiscing.
\tiny Phasellus placerat. In sem nisl, elementum vitae, venenatis nec, lacinia
Duis viverra. Nulla diam lectus, tincidunt et, scelerisque vitae, aliquam
vitae, justo. Quisque eget erat. Donec aliquet porta magna. Sed nisl. Ut
tellus. Suspendisse quis mi eget dolor sagittis tristique. Aenean non pede eget
nisl bibendum gravida. Class aptent taciti sociosqu ad litora torquent per
conubia nostra, per inceptos himenaeos. Morbi laoreet. Suspendisse potenti.
Nec, varius consectetuer, lorem.








[^10]: Si intende una sequenza $\infty$ di configurazioni.
[^11]: Nella formalizzazione del linguaggio salta subito all'occhio che automi e MdT sono rappresentati come stringhe. Per fare questo è necessaria una corrispondenza biunivoca tra macchina e codifica della macchina di cui non ho ancora fatto menzione. Per adesso è sufficiente sapere che ogni macchina può essere codificata con una stringa e che ogni stringa rappresenta una macchina. Le codifiche saranno rappresentate come n-uple di stringhe tra parentesi a diamante: $\langle cod_1, cod_2, ... \rangle$.
[^12]: $A_{MdT}$ è indecidibile
\begin{equation*}
A_{MdT} = \{\langle M,w\rangle\ |\ \text{$M$ è un MdT che accetta la stringa in input $w$}\}
\end{equation*}
